=begin
#Team Worldwide API 2022

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuthenticateApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthenticateApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthenticateApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticateApi' do
    it 'should create an instance of AuthenticateApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthenticateApi)
    end
  end

  # unit tests for post_credentials_item
  # Authenticate to start session.
  # @param [Hash] opts the optional parameters
  # @option opts [Credentials] :body Start Session
  # @return [nil]
  describe 'post_credentials_item test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
