=begin
#Team Worldwide API 2022

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InvoicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InvoicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InvoicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicesApi' do
    it 'should create an instance of InvoicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InvoicesApi)
    end
  end

  # unit tests for get_get_invoice_item
  # Get invoice by house bill
  # Retrieves a GetInvoice resource.
  # @param house_bill Resource identifier
  # @param [Hash] opts the optional parameters
  # @return [GetInvoiceInvoiceJsonldInvoiceItemGetRead]
  describe 'get_get_invoice_item test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
