=begin
#Team Worldwide API 2022

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::OneOfProjectedCustomerChargeJsonldShipmentCreateContext
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OneOfProjectedCustomerChargeJsonldShipmentCreateContext' do
  before do
    # run before each test
    @instance = SwaggerClient::OneOfProjectedCustomerChargeJsonldShipmentCreateContext.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OneOfProjectedCustomerChargeJsonldShipmentCreateContext' do
    it 'should create an instance of OneOfProjectedCustomerChargeJsonldShipmentCreateContext' do
      expect(@instance).to be_instance_of(SwaggerClient::OneOfProjectedCustomerChargeJsonldShipmentCreateContext)
    end
  end
end
