=begin
#Team Worldwide API 2022

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead' do
  before do
    # run before each test
    @instance = SwaggerClient::RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead' do
    it 'should create an instance of RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead' do
      expect(@instance).to be_instance_of(SwaggerClient::RateNoDataJsonldTeamBookGetRateCreateCollectionGetRead)
    end
  end
  describe 'test attribute "context"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "vendor"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "response"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
